apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
  name: cloud-credential-operator-alerts
  namespace: openshift-cloud-credential-operator
spec:
  groups:
  - name: CloudCredentialOperator
    rules:
    - alert: CloudCredentialOperatorTargetNamespaceMissing
      annotations:
        message: CredentialsRequest(s) pointing to non-existent namespace
      expr: cco_credentials_requests_conditions{condition="MissingTargetNamespace"}
        > 0
      for: 5m
      labels:
        severity: warning
    - alert: CloudCredentialOperatorProvisioningFailed
      annotations:
        message: CredentialsRequest(s) unable to be fulfilled
      expr: cco_credentials_requests_conditions{condition="CredentialsProvisionFailure"}
        > 0
      for: 5m
      labels:
        severity: warning
    - alert: CloudCredentialOperatorDeprovisioningFailed
      annotations:
        message: CredentialsRequest(s) unable to be cleaned up
      expr: cco_credentials_requests_conditions{condition="CredentialsDeprovisionFailure"}
        > 0
      for: 5m
      labels:
        severity: warning
    - alert: CloudCredentialOperatorInsufficientCloudCreds
      annotations:
        message: Cluster's cloud credentials insufficient for minting or passthrough
      expr: cco_credentials_requests_conditions{condition="InsufficientCloudCreds"}
        > 0
      for: 5m
      labels:
        severity: warning
    - alert: CloudCredentialOperatorStaleCredentials
      annotations:
        message: 1 or more credentials requests are stale and should be deleted. Check the status.conditions on CredentialsRequest CRs to identify the stale one(s).
      expr: cco_credentials_requests_conditions{condition="StaleCredentials"}
        > 0
      for: 5m
      labels:
        severity: warning
